# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4a4db4f4197fb7dd11805854e393602be6f4fa7ba294b253c0baa7f0343f59473c12a73246004b7b7e8031a2cf23b2620de35fab1e6d369938fb9033a9ac72

test:
  secret_key_base: 80b34d4332fb66825003c5acac6c361262884822f41fed9b092d8ba8e8625c7f3378ea6f2b95e431fc205636b4e12785d84c6d77fd8538bb5651971decd7f06f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
